### ISSUE TITLE
Feature: Authentication support

### ISSUE THREAD

**Issue by shawnbutts** [bbb31/mjb#1]
Sometimes, JMX has to be setup for authentication

**Comment by bbb31** [comment]
I need more details on this.

**Comment by bbb31** [comment]
Shouldnt be hard to implement after looking over [this](https://docs.oracle.com/cd/E19717-01/819-7758/gchjy/index.html).

**Comment by bbb31** [comment]
@shawnbutts if I was to implement this would you be able to test it?

**Comment by shawnbutts** [comment]
Yes, i can test it.

It should also be simple enough to test using `com.sun.management.jmxremote.access.file` variable for any given JMX setup.

**Comment by bbb31** [comment]
@shawnbutts see latest 1.1 release: https://github.com/bbb31/mjb/releases/tag/1.1

**Comment by bbb31** [comment]
I believe this is fixed, so going to close.
